### ISSUE TITLE
Setting headers with request ?

### ISSUE THREAD

**Issue by anasvn** [cubiclesoft/jquery-fancyfileuploader#8]
I need to set headers for security purpose. Do I have any options to set custom headers ?

**Comment by cubiclesoft** [comment]
Sure!  There are several options:

https://stackoverflow.com/questions/10011828/jquery-file-upload-by-blueimp-additional-headers

Note that jQuery Fancy File Uploader is a wrapper around the blueimp jQuery File Uploader.  Most of the options for that plugin are able to be set via the 'fileupload' option.  Some of the callbacks are immutable, (e.g. "add") because they are overridden by this plugin.  However, this plugin has plenty of callbacks too (e.g. "added") that passes along the same data as the original callback so many/all of the same suggestions in the above post will work fine.
